name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
